### ISSUE TITLE
Replace deprecated Eclipse Aether with Apache Maven Artifact Resolver

### ISSUE THREAD

**Issue by tMaxx** [Knotx/knotx-stack#21]
Eclipse Aether is now Apache Maven Artifact Resolver: https://maven.apache.org/resolver/

There are some hints that new project is backwards binary compatible, so for the most part it should be a matter of switching to new package names.

References:
- https://projects.eclipse.org/projects/technology.aether
- http://maven.40175.n5.nabble.com/Formerly-Aether-now-Maven-Artifact-Resolver-documentation-td5900927.html
- https://projects.eclipse.org/projects/technology.aether/reviews/termination-review

**Comment by tomaszmichalak** [comment]
We plan to switch from Maven to Gradle. This task would not be required.

**Comment by tomaszmichalak** [comment]
Invalid.
