### ISSUE TITLE
Host header removed from default HTTP repo connector allowed headers

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx-stack#40]
**Describe the bug**
In #39 [`Host` header was removed from `allowedRequestHeaders`](https://github.com/Knotx/knotx-stack/pull/39/files#diff-7acd6dbad10d469d8c6c198c3d1d17d7) because of failing integration tests.

Investigate and bring back `Host` header to default values of `allowedRequestHeaders` again.

**To Reproduce**
1. Add `Host` to `allowedRequestHeaders` in `httpRepoConnectorHandler.conf`
2. Run the tests
3. See failed tests

**Expected behavior**
Tests pass with `Host` header.

**Comment by dragarth-7** [comment]
@Skejven Is this issue is still valid ?

I see "Host" value in allowedRequestHeaders in httpRepoConnectorHandler.conf file.

**Comment by Skejven** [comment]
Looks like this is fixed, tests have `Host` in the:
https://github.com/Knotx/knotx-stack/blame/master/src/functionalTest/resources/conf/routes/handlers/httpRepoConnectorHandler.conf

Looks that it was fixed in #54 , thanks!
