### ISSUE TITLE
Execute tests from all included builds

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-stack#57]
**Describe the bug**
Execute all Unit tests during the Gradle composite build execution.

**To Reproduce**
1. `git clone git@github.com:Knotx/knotx-aggregator.git`
2. `cd knotx-aggregator/development/`
3. `mkdir knotx`
4. `sh pull-all.sh -r ./knotx`
5. `cd knotx/knotx-stack`
6. `./gradlew test`
7. `idea .`
8. modify assertions in io.knotx.fragments.engine.TaskEngineSingleOperationTest
9. `./gradlew test` is success

**Expected behavior**
9. `./gradlew test` should fail

**Additional context**
- https://docs.gradle.org/current/userguide/composite_builds.html#included_build_task_dependencies

**Comment by tomaszmichalak** [comment]
This is still valid, we made some simple fix but better solution is expected.

**Comment by Skejven** [comment]
Fixed by #116 
use `./gradlew check`
