### ISSUE TITLE
knotx script issue on docker in Windows

### ISSUE THREAD

**Issue by marcinkp** [Knotx/knotx-stack#65]
**Describe the bug**
You cannot build stack and docker image on windows machine without issue. 

**To Reproduce**
Steps to reproduce the behavior run on Windows:
1. Checkout `knotx-aggregator`
2. Go to `knotx-aggregator/development`
3. `./pull-all.sh -r ../..`
4. `./build-stack.sh -r ../..`
5. Go to `knotx-docker` project and build image `mvn clean install`
6. Go to `knotx-starter-kit`
7. Run `./gradlew build-docker`

there will be issue **FAILURE: Build failed with an exception**.
Logs from knotx:
`standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Expected behavior**
Possibility to build own knotx images

**Comment by dragarth-7** [comment]
@marcinkp Are you checked if you have any files with CRLF ?

If you somehow have files with CRLF, you should change them from CRLF to LF.
