### ISSUE TITLE
Create functional tests for http action

### ISSUE THREAD

**Issue by oskarjerzyk** [Knotx/knotx-stack#66]
The idea of this ticket is to create functional tests regarding http action. We would like to test behavior of this action in real case scenario and test cooperation with for example circuit breaker. In the scope of this ticket we have to create appropriate configs and http actions calling endpoints with mocked data, checking if handling responses, errors and fallbacks work correctly in our system

**Comment by tomaszmichalak** [comment]
The first scenario covers:
> (user) -_s-> [ (payments), (offers*) -_e-> (offers-fallback) ] -> (response)
> \* - means error

**Comment by tomaszmichalak** [comment]
The next scenario (with circuit breaker action) should covers:
> (user) -_s-> [ (payments), (cb(offers*)) -_e-> (offers-fallback) ] -> (response)
> \* - means timeout from HTTP Action
> cb is configured with retry = 1

> (user) -_s-> [ (payments), (cb(offers*)) ] -> (response)
> \* - means timeout from CB (configured in circuitBreakerOptions.timeout), second offers service invocation should end with success
> cb is configured with retry = 1

@Skejven what do you think about those two scenarios?

**Comment by Skejven** [comment]
In the CB scenario, cb returns `_f` (fallback) not `_e`.
Otherwise, scenarios are ok 👍 .
